=== 201265615/TP4_BD2_I15_ORACLE_XML/XSD/FacturasCompra.xsd
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xdb="http://xmlns.oracle.com/xdb"
  version="1.0"
  xdb:storeVarrayAsTable="true">
  <xs:element name="FacturaCompra" type="FacturaCompraType" xdb:defaultTable="FACTURAS_TABLE"/>
  <xs:complexType name="FacturaCompraType" xdb:SQLType="FACTURACOMPRAS_TYPE">
    <xs:sequence>
      <xs:element name="NumeroFactura" type="NumeroFacturaType"/>
      <xs:element name="FechaCompra" type="FechaCompraType"/>
      <xs:element name="Proveedor" type="ProveedorType"/>
      <xs:element name="Usuario" type="UsuarioType" minOccurs="1"/>
      <xs:element name="LineasFactura" type="LineasFacturasType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LineasFacturasType" xdb:SQLType="LISTALINEASFACTURA">
    <xs:sequence>
      <xs:element name="LineaFactura" type="LineaFacturaType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LineaFacturaType" xdb:SQLType="LINEAFACTURA_TYPE">
    <xs:sequence>
      <xs:element name="Articulo" type="ArticuloType"/>
    </xs:sequence>
    <xs:attribute name="NumeroLineaFactura" type="xs:integer"
                  xdb:SQLType="NUMBER"/>
  </xs:complexType>
  <xs:complexType name="ArticuloType" xdb:SQLType="ARTICULO_TYPE">
    <xs:attribute name="Codigo" xdb:SQLType="VARCHAR2">
      <xs:simpleType>
        <xs:restriction base="xs:string"/>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="Descripcion" type="DescripcionType" xdb:SQLType="VARCHAR2"/>
    <xs:attribute name="PrecioMercDolares" type="MonedaType" xdb:SQLType="DECIMAL"/>
    <xs:attribute name="UnidadMedida" type="UnidadMedidaType" xdb:SQLType="VARCHAR2"/>
    <xs:attribute name="Marca" type="MarcaType"/>
    <xs:attribute name="Familia" type="FamiliaType"/>
    <xs:attribute name="Cantidad" type="CantidadType"/>
    <xs:attribute name="CantMaxima" type="CantidadType"/>
    <xs:attribute name="CantMinima" type="CantidadType"/>
    <xs:attribute name="EstadoArticulo" type="EstadoArticuloType"/>
  </xs:complexType>
  <xs:simpleType name="MonedaType">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="2"/>
      <xs:totalDigits value="17"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CantidadType">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="4"/>
      <xs:totalDigits value="8"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UsuarioType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="10"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="ProveedorType">
    <xs:restriction base="xs:string">
      <xs:minLength value="0"/>
      <xs:maxLength value="128"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="NumeroFacturaType">
    <xs:restriction base="xs:integer"/>
  </xs:simpleType>
  <xs:simpleType name="DescripcionType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="256"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="UnidadMedidaType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="10"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="FamiliaType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="10"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="MarcaType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="10"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EstadoArticuloType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="10"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="FechaCompraType">
    <xs:restriction base="xs:date"/>
  </xs:simpleType>
</xs:schema>

=== 201265615/TP4_BD2_I15_ORACLE_XML/2015/Factura001.xml
<?xml version="1.0" encoding="UTF-8" ?>
<FacturaCompra xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://172.19.127.101:9090/grupo01/Facturas/xsd/FacturasCompra.xsd">
  <NumeroFactura>1</NumeroFactura>
  <FechaCompra>2015-06-09</FechaCompra>
  <Proveedor>CompuFax</Proveedor>
  <Usuario>Admin</Usuario>
  <LineasFactura>
    <LineaFactura NumeroLineaFactura="1">
      <Articulo Codigo="FP110" Cantidad="12" CantMaxima="40" CantMinima="5" Descripcion="Fuente de poder"
       EstadoArticulo="Activo" Familia="CPU" Marca="HP" PrecioMercDolares="50" UnidadMedida="un"/>
    </LineaFactura>
    <LineaFactura NumeroLineaFactura="2">
      <Articulo Codigo="FTCO2175" Cantidad="30" CantMaxima="46" CantMinima="1" Descripcion="Pantalla Plana 21 pul"
       EstadoArticulo="Activo" Familia="Monitores" Marca="Toshiba" PrecioMercDolares="100" UnidadMedida="un"/>
    </LineaFactura>
    <LineaFactura NumeroLineaFactura="3">
      <Articulo Codigo="INCOHO" Cantidad="33" CantMaxima="40" CantMinima="7" Descripcion="Impresora Color"
       EstadoArticulo="Activo" Familia="Impresoras" Marca="Lexmark" PrecioMercDolares="56" UnidadMedida="un"/>
    </LineaFactura>
  </LineasFactura>
</FacturaCompra>

=== 201265615/TP4_BD2_I15_ORACLE_XML/2015/Factura002.xml
<?xml version="1.0" encoding="UTF-8" ?>
<FacturaCompra xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://172.19.127.101:9090/grupo01/Facturas/xsd/FacturasCompra.xsd">
  <NumeroFactura>2</NumeroFactura>
  <FechaCompra>2015-06-12</FechaCompra>
  <Proveedor>OfficeDepot</Proveedor>
  <Usuario>Admin</Usuario>
  <LineasFactura>
    <LineaFactura NumeroLineaFactura="1">
      <Articulo Codigo="MSBT1" Cantidad="12" CantMaxima="40" CantMinima="5" Descripcion="Mouse bluetooth"
       EstadoArticulo="Activo" Familia="CPU" Marca="Dell" PrecioMercDolares="10" UnidadMedida="un"/>
    </LineaFactura>
    <LineaFactura NumeroLineaFactura="2">
      <Articulo Codigo="RTC1800" Cantidad="10" CantMaxima="20" CantMinima="1" Descripcion="Router Cisco 1800"
       EstadoArticulo="Activo" Familia="Enrutador" Marca="Cisco" PrecioMercDolares="200" UnidadMedida="un"/>
    </LineaFactura>
	<LineaFactura NumeroLineaFactura="3">
      <Articulo Codigo="UPS110" Cantidad="5" CantMaxima="10" CantMinima="1" Descripcion="UPS 110v"
       EstadoArticulo="Activo" Familia="Baterias" Marca="FPC" PrecioMercDolares="100" UnidadMedida="un"/>
    </LineaFactura>
	<LineaFactura NumeroLineaFactura="4">
      <Articulo Codigo="PE2" Cantidad="30" CantMaxima="50" CantMinima="10" Descripcion="Parlantes escritorio"
       EstadoArticulo="Activo" Familia="CPU" Marca="SoundAlive" PrecioMercDolares="50" UnidadMedida="un"/>
    </LineaFactura>
  </LineasFactura>
</FacturaCompra>

=== 201265615/TP4_BD2_I15_ORACLE_XML/2015/Factura008.xml
<?xml version="1.0" encoding="UTF-8" ?>
<FacturaCompra xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://172.19.127.101:9090/grupo01/Facturas/xsd/FacturasCompra.xsd">
  <NumeroFactura>1</NumeroFactura>
  <FechaCompra>2015-06-12</FechaCompra>
  <Proveedor>COCOCO</Proveedor>
  <Usuario>Admin</Usuario>
  <LineasFactura>
    <LineaFactura NumeroLineaFactura="1">
      <Articulo Codigo="INCOHO" Cantidad="45" CantMaxima="50" CantMinima="17" Descripcion="Impresora Color Multiuso"
       EstadoArticulo="Activo" Familia="Impresoras" Marca="Brother" PrecioMercDolares="486" UnidadMedida="un"/>
    </LineaFactura>
      <LineaFactura NumeroLineaFactura="2">
      <Articulo Codigo="TEIG" Cantidad="45" CantMaxima="10" CantMinima="7" Descripcion="Teclado Inalambrico Gamer"
       EstadoArticulo="Activo" Familia="Teclados" Marca="Logitech" PrecioMercDolares="86" UnidadMedida="un"/>
    </LineaFactura>
  </LineasFactura>
</FacturaCompra>

=== 201265615/TP4_BD2_I15_ORACLE_XML/2015/Factura007.xml
<?xml version="1.0" encoding="UTF-8" ?>
<FacturaCompra xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://172.19.127.101:9090/grupo01/Facturas/xsd/FacturasCompra.xsd">
  <NumeroFactura>1</NumeroFactura>
  <FechaCompra>2015-06-12</FechaCompra>
  <Proveedor>Compuamersa</Proveedor>
  <Usuario>Admin</Usuario>
  <LineasFactura>
    <LineaFactura NumeroLineaFactura="1">
      <Articulo Codigo="FP110" Cantidad="8" CantMaxima="20" CantMinima="5" Descripcion="Fuente de poder"
       EstadoArticulo="Activo" Familia="CPU" Marca="Corsair" PrecioMercDolares="250" UnidadMedida="un"/>
    </LineaFactura>
    <LineaFactura NumeroLineaFactura="=2">
      <Articulo Codigo="INCOHO" Cantidad="15" CantMaxima="30" CantMinima="7" Descripcion="Impresora Color"
       EstadoArticulo="Activo" Familia="Impresoras" Marca="Epson" PrecioMercDolares="506" UnidadMedida="un"/>
    </LineaFactura>
     <LineaFactura NumeroLineaFactura="=3">
      <Articulo Codigo="SCA" Cantidad="5" CantMaxima="10" CantMinima="2" Descripcion="Scanner"
       EstadoArticulo="Activo" Familia="Scanner" Marca="Epson" PrecioMercDolares="306" UnidadMedida="un"/>
    </LineaFactura>
  </LineasFactura>
</FacturaCompra>

=== 201265615/TP4_BD2_I15_ORACLE_XML/2015/Factura006.xml
<?xml version="1.0" encoding="UTF-8" ?>
<FacturaCompra xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://172.19.127.101:9090/grupo01/Facturas/xsd/FacturasCompra.xsd">
  <NumeroFactura>1</NumeroFactura>
  <FechaCompra>2015-06-12</FechaCompra>
  <Proveedor>ATEK</Proveedor>
  <Usuario>Admin</Usuario>
  <LineasFactura>
    <LineaFactura NumeroLineaFactura="1">
      <Articulo Codigo="FTCO2175" Cantidad="10" CantMaxima="26" CantMinima="2" Descripcion="Pantalla Plana 21 pulg"
       EstadoArticulo="Activo" Familia="Monitores" Marca="Sony" PrecioMercDolares="1000" UnidadMedida="un"/>
    </LineaFactura>
    <LineaFactura NumeroLineaFactura="2">
      <Articulo Codigo="INCOHO" Cantidad="12" CantMaxima="20" CantMinima="7" Descripcion="Impresora Color"
       EstadoArticulo="Activo" Familia="Impresoras" Marca="HP" PrecioMercDolares="570" UnidadMedida="un"/>
    </LineaFactura>
     <LineaFactura NumeroLineaFactura="3">
      <Articulo Codigo="MOI" Cantidad="10" CantMaxima="20" CantMinima="7" Descripcion="Mouse Inalambrico"
       EstadoArticulo="Activo" Familia="Mouses" Marca="Dell" PrecioMercDolares="70" UnidadMedida="un"/>
    </LineaFactura>
  </LineasFactura>
</FacturaCompra>
